import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const foundationRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

export function parseConsumerArgument(argv) {
  const index = argv.indexOf("--consumer");
  if (index === -1 || !argv[index + 1]) {
    throw new Error("Usage: node tooling/<sync|check>.mjs --consumer <path>");
  }
  return path.resolve(argv[index + 1]);
}

async function read(relativePath) {
  return readFile(path.join(foundationRoot, relativePath), "utf8");
}

export async function composeAgents(consumerDirectory) {
  const [template, core, profile, product] = await Promise.all([
    read("templates/AGENTS.md"),
    read("policy/core.md"),
    read("profiles/next-supabase/project-rules.md"),
    readFile(path.join(consumerDirectory, ".ai-dev-foundation", "product-rules.md"), "utf8"),
  ]);

  return `${template.trim()}\n\n<!-- GENERATED by ai-dev-foundation. Run sync; do not edit. -->\n\n## Foundation policy\n\n${core.trim()}\n\n## Technology profile: Next.js + Supabase\n\n${profile.trim()}\n\n## Consumer product rules\n\n${product.trim()}\n`;
}

export async function composeClaude() {
  return read("templates/CLAUDE.md");
}
