import { cp, mkdir, readdir, readFile, rm } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const foundationRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const qualityProfileSourceDirectory = path.join(foundationRoot, "profiles", "next-supabase", "quality");
export const skillsSourceDirectory = path.join(foundationRoot, "skills");

export function parseConsumerArgument(argv) {
  const index = argv.indexOf("--consumer");
  if (index === -1 || !argv[index + 1]) {
    throw new Error("Usage: node tooling/<sync|check>.mjs --consumer <path>");
  }
  return path.resolve(argv[index + 1]);
}

async function read(relativePath) {
  return readFile(path.join(foundationRoot, relativePath), "utf8");
}

export async function composeAgents(consumerDirectory) {
  const [template, core, profile, product] = await Promise.all([
    read("templates/AGENTS.md"),
    read("policy/core.md"),
    read("profiles/next-supabase/project-rules.md"),
    readFile(path.join(consumerDirectory, ".ai-dev-foundation", "product-rules.md"), "utf8"),
  ]);

  return `${template.trim()}\n\n<!-- GENERATED by ai-dev-foundation. Run sync; do not edit. -->\n\n## Foundation policy\n\n${core.trim()}\n\n## Technology profile: Next.js + Supabase\n\n${profile.trim()}\n\n## Consumer product rules\n\n${product.trim()}\n`;
}

export async function composeClaude() {
  return read("templates/CLAUDE.md");
}

// Lists every non-directory entry (regular file, symlink — broken or not)
// under `directory` as sorted, POSIX-separated paths relative to it. Uses
// Dirent typing rather than "try to read it" so a broken symlink is still
// reported as an entry instead of being mistaken for a missing directory.
async function listRelativeEntries(directory) {
  let entries;
  try {
    entries = await readdir(directory, { recursive: true, withFileTypes: true });
  } catch (error) {
    if (error.code === "ENOENT") return [];
    throw error;
  }
  return entries
    .filter((entry) => !entry.isDirectory())
    .map((entry) => path.join(entry.parentPath, entry.name))
    .map((absolutePath) => path.relative(directory, absolutePath).split(path.sep).join("/"))
    .sort();
}

// Only ENOENT (missing file, or a symlink whose target doesn't exist) is
// treated as "no content"; any other read failure (e.g. permissions) is a
// real problem and must not be silently reported as ordinary content drift.
async function readContentOrNull(filePath) {
  try {
    return await readFile(filePath, "utf8");
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

// Compares a Foundation-owned exact-match source directory against a
// consumer's materialized copy. Missing, mismatched, and stale-extra files
// (nested subdirectories included) are all reported as drift, so a repin
// without re-materializing that directory cannot pass.
export async function diffOwnedDirectory(sourceDirectory, destinationDirectory) {
  const [sourceRelativePaths, destinationRelativePaths] = await Promise.all([
    listRelativeEntries(sourceDirectory),
    listRelativeEntries(destinationDirectory),
  ]);
  const destinationRelativePathSet = new Set(destinationRelativePaths);
  const drifted = new Set();

  for (const relative of sourceRelativePaths) {
    if (!destinationRelativePathSet.has(relative)) {
      drifted.add(relative); // missing in consumer
      continue;
    }
    const [sourceContent, destinationContent] = await Promise.all([
      readContentOrNull(path.join(sourceDirectory, ...relative.split("/"))),
      readContentOrNull(path.join(destinationDirectory, ...relative.split("/"))),
    ]);
    if (sourceContent !== destinationContent) drifted.add(relative);
  }

  const sourceRelativePathSet = new Set(sourceRelativePaths);
  for (const relative of destinationRelativePaths) {
    if (!sourceRelativePathSet.has(relative)) drifted.add(relative); // stale extra entry
  }

  return [...drifted].sort();
}

// profiles/next-supabase/quality against a bootstrapped consumer's
// .ai-dev-foundation/quality.
export async function diffQualityProfile(consumerDirectory) {
  return diffOwnedDirectory(
    qualityProfileSourceDirectory,
    path.join(consumerDirectory, ".ai-dev-foundation", "quality"),
  );
}

// Foundation-owned skills/ against a synced consumer's
// .ai-dev-foundation/skills.
export async function diffSkillBundle(consumerDirectory) {
  return diffOwnedDirectory(skillsSourceDirectory, path.join(consumerDirectory, ".ai-dev-foundation", "skills"));
}

// Replaces destinationDirectory with an exact copy of sourceDirectory
// (missing, mismatched, and stale-extra entries are all removed/overwritten).
// Only safe for directories that are entirely Foundation-owned exact-match
// content, never for a path that may also hold consumer-owned files.
export async function materializeOwnedDirectory(sourceDirectory, destinationDirectory) {
  await Promise.all([
    rm(destinationDirectory, { recursive: true, force: true }),
    mkdir(path.dirname(destinationDirectory), { recursive: true }),
  ]);
  await cp(sourceDirectory, destinationDirectory, { recursive: true });
}
